ALL_PROJECTS = "SELECT * FROM project;"
ALL_TASKS = "SELECT * FROM task;"
ALL_CURRENCIES = "SELECT * FROM currency;"
ALL_MEMBERS = "SELECT * FROM member;"
JOIN_PROJECT_AND_TASK="SELECT project.*, task.name AS task_name FROM project INNER JOIN task ON project.id = task.projectId;"
TASK_JOIN_TASKCOSTITEM_JOIN_COSTITEM = "select * from task t join taskCostItem tc on t.id = tc.taskId and t.projectId = tc.projectId join costItem c on c.id = tc.costItemId"