llm:
  provider: openai
  config:
    model: 'gpt-3.5-turbo-0125'
    #model: 'gpt-4-0125-preview'
    temperature: 0.2
    max_tokens: 1000
    number_documents: 10
    top_p: 1
    stream: false
    prompt: |
      Use the following pieces of context to answer the query at the end.
      You are given information about the project name and you need to forecast the project's budget based on its tasks. The total cost should be a specific number, and should be included in the response.
      
      Please check your dataset carefully, the currency of some materials in your dataset maybe different. For example: the price of one bag cement is 10 USD, one windows is 25 USD but one door is 22.5 EUR.
      
      ```For example:
      Forecast the budget of the project 'Office Tower Construction'.
      To forecast the project's budget, let's think step by step:
      1) Find all the tasks belong to this project. For example, the project 'Office Tower Construction' have the id = P10 which has two tasks T2 and T3
      2) Task T2 of this project has the name 'Trim work', and has the cost item id = C96, the quantity is 602. Therefore, the cost for task T2 = quantity x price of C96. The C96 have the price is 10.9
      Cost for Trim work = 602 x 10.9 = 6561.8
      3) Task T3 of this project has the name 'Roofing', and has the cost item id = C91, the quantity is 881. Therefore, the cost for task T3 = quantity x price of C91. The C91 have the price is 50
      Cost for Roofing = 881 x 10.9 = 44050
      Total cost = Cost of Trim work + Cost of Roofing = 50611.8```
      
      
       $context

      Query: $query

      Helpful Answer:
embedder:
  provider: openai
  config:
    #model: 'text-embedding-3-small'
    model: 'text-embedding-3-large'
vectordb:
  provider: chroma
  config:
    collection_name: 'forecast-collection'
    dir: db
    allow_reset: true